---
version: "3"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - data:/path/to/data:/config
    ports:
      - 80:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freshrss.rule=Host(`DOMAINNAME`)"
      - "traefik.http.routers.freshrss.entrypoints=web"
volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.X,rw
networks:
  network1:
    name: nfs_default
    external: true
